sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - 'lander --upload --ltd-product dmtr-141 --pdf DMTR-141.pdf --env travis --lsstdoc DMTR-141.tex --abstract "This brief report describes measurements of interest that were carried out for release v18.0.0 of the Science Pipeline."'
env:
  global:
    - secure: "Og4/0mdBs6xhpoV1LcaOAe2MnzzVLj4wmbbRkqOI7cODEoyyRe4YMEpl7sk3qO/ojDGRmhhtVqf9b0j67kRwCqvwqX0UmgPc87MNi4Ma7WBHv7xWfpLotR/ePH1EjnCFF7NbY0hgRfNFRdAEY+gfkJlbUb7IpoxeZF27/k9LX7vTcGFobV795KNrxxBLoGSfO6Z+4W25S431gtE46dxsZCDp0/D7F+/KSg1LdY3gv9VoPD67dxxOUFeBG9zyYPRzA15GxxIfvUvoGZSEt03o/p4DVDkPRseyASkyu+ybtSzh7GiwPj19n/6JwRnTWZTsYP8qRmCloo2X9FE/QkXIG5m+p2+oL8pCUCsvLTUMDwDPXrIYRM3kra2mzQGJg5pMj9k9qu0MCbqMwM+w82ljAbxa7eugWkXLUeYnLuHWiBYGNZfUAN9IOwn2aREAgB9lwvb4Uu2VS3C0G4xW6jwtlHvNfleQ84DDPz7Uq242xPDgApHQwQytI0qj0nRpwPA380jFyEd36vBawW6KR+mYjYJMbrKs5xR3+FhHiLqsFw+dr5/tietw/wlRq9MVEerA01m+rpl54nE6PLHABc5C8ESCsNsNFoqQVeZez1dtindP9D+5xRX6zRWKjmuQHGQ2VzGiE6xAjDFdU1BF9VhNNU+6IBXeTZ1LrOBwS5MzVxA="
    - secure: "lJdtzbxykG/8K/oCeOAqxPtEm6BnzOJ44kT/UpJChSfDGlkhyOHu2t8ZQ2PHj/rbRxWirjVIrnHnzRdqwuheItq5KYXVAk7k6cZnxTyyGT9LcS+6rCeSx18ceeNU/3MVbIOCVT9KY4fJEO99omfx+ujflVU363Q9b/shmHWBvVSjth58CaZZc0gFSIl0PR/ee5i6jWEFR6UGo3OelXbUmBNzxVr+K3x8BzY0K0kxs/bb3jdP5e9vx0XsMvjX2al4mZUwjl5dPnL3p1CdxMvfa6Gls4HLt6BmgpT7+pHixz4yPxTTAHiM8+0J6L2z36k7uJUVl8IohywFeR+v2EqqBuoSqTJGMiVZssvx8M+C1p1dBSO0w4I8E5WSuTG+slK/KpGPMnm6mpRr6f0BYXZXe9f1DzojYJ3rfB0QCGwoBw4DATfrzjkY/oVLALYGz80vwyNiamYa3tI6mZmAxkBOA2ibpFsZOs6BL+mYCsyxdqzCxfRirLGyLYDqK0jUePgshxgGlnwPpZZHYXIceiqLrJPl8RalBnz8TYsnI8HG6r8aGGEe/aYNxvIq/k9IbnZZn/dIKF1eKakwBkZ73r6mn1oB4L82Mdk94y+OdnAF/BXITy5i4xWhZ/sLlratySvUWQfC3I8DeRYigRgUQ246y9gBsHxAf0UMh61EfA5IRfQ="
